services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /app/.venv
    command: >
      bash -c "alembic upgrade head
      && python -m src.main"
    environment:
      DATABASE__HOST: db
      DATABASE__USER: postgres
      DATABASE__PASSWORD: mypassword
      DATABASE__DB: postgres_db
      IS_DEBUG: True
    stdin_open: true
    tty: true
    networks:
      - default_network
    depends_on:
      - db

  db:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - default_network

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - default_network

networks:
  default_network:
    
volumes:
  pg_data:
  pgadmin_data:
